export const TEX = {
  HERO:       'hero',
  GROUND:     'ground',
  RURAL_BG:   'rural',
  URBAN_BG:   'city-bg',
  WOLF:       'wolf',
  FAT_CAT:    'fatcat',
  LASER:      'laser',
  HP_ICON:    'hp-icon',
  HELICOPTER: 'helicopter',
  NINJA:      'ninja',
  AIRPLANE:   'airplane',
  BOMB:       'bomb',
  LIMO:       'limo',
  BUS:        'bus',
  BOSS_WOLF:  'boss-wolf',
  BOSS_CAT:   'boss-cat',
} as const
